package com.spiceflow.backend.events;

/**
 * Vocabulary of domain events emitted by operational workflows.
 */
public enum DomainEventType {
    PURCHASE_ORDER_CREATED,
    PURCHASE_ORDER_SUBMITTED,
    PURCHASE_ORDER_APPROVED,
    PURCHASE_ORDER_REJECTED,
    PURCHASE_ORDER_ORDERED,
    PURCHASE_ORDER_PARTIALLY_RECEIVED,
    PURCHASE_ORDER_RECEIVED,
    PURCHASE_ORDER_CLOSED,
    GOODS_RECEIPT_CREATED,
    GOODS_RECEIPT_VERIFIED,
    GOODS_RECEIPT_POSTED,
    GOODS_RECEIPT_CANCELLED,
    GOODS_RECEIVED,
    INVENTORY_ADJUSTED,
    WAREHOUSE_TRANSFER_REQUESTED,
    WAREHOUSE_TRANSFER_APPROVED,
    WAREHOUSE_TRANSFER_SHIPPED,
    WAREHOUSE_TRANSFER_RECEIVED,
    WAREHOUSE_TRANSFER_COMPLETED,
    WAREHOUSE_TRANSFER_CANCELLED,
    REP_ORDER_CREATED,
    REP_ORDER_SUBMITTED,
    REP_ORDER_APPROVED,
    REP_ORDER_LOADED,
    REP_ORDER_DELIVERED,
    REP_ORDER_CANCELLED,
    LOADING_SHEET_GENERATED,
    LOADING_SHEET_CONFIRMED,
    LOADING_SHEET_CANCELLED,
    DELIVERY_DISPATCHED,
    DELIVERY_COMPLETED,
    DELIVERY_CANCELLED,
    CASH_COLLECTED
}
