CREATE TABLE final_balances (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tenant_id BIGINT NOT NULL,
    rep_id BIGINT NOT NULL,
    driver_id BIGINT,
    balance_date DATE NOT NULL,
    
    morning_summary_value DECIMAL(12,2) NOT NULL DEFAULT 0.00,
    cancel_summary_value DECIMAL(12,2) NOT NULL DEFAULT 0.00,
    total_bill_collections DECIMAL(12,2) NOT NULL DEFAULT 0.00,
    mismatch_value DECIMAL(12,2) NOT NULL DEFAULT 0.00,
    
    status VARCHAR(50) NOT NULL,
    remarks TEXT,
    
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    created_by BIGINT,
    updated_by BIGINT,
    
    CONSTRAINT fk_final_balances_tenant FOREIGN KEY (tenant_id) REFERENCES tenants(id),
    CONSTRAINT fk_final_balances_rep FOREIGN KEY (rep_id) REFERENCES users(id),
    CONSTRAINT fk_final_balances_driver FOREIGN KEY (driver_id) REFERENCES drivers(id)
);

CREATE INDEX idx_final_balances_tenant ON final_balances(tenant_id);
CREATE INDEX idx_final_balances_rep ON final_balances(rep_id);
CREATE INDEX idx_final_balances_date ON final_balances(balance_date);
