package com.spiceflow.backend.workflow;

import com.spiceflow.backend.events.DomainEvent;
import java.util.List;

/**
 * Interface implemented by operational aggregates that undergo finite state machine transitions.
 *
 * @param <S> The workflow state type
 */
public interface WorkflowAggregate<S extends WorkflowState> {
    /**
     * Unique identifier of the aggregate (e.g., PO ID or string code).
     */
    String getAggregateId();

    /**
     * Returns the current workflow state of the aggregate.
     */
    S getWorkflowState();

    /**
     * Transitions the aggregate to the target state.
     * Called exclusively by WorkflowEngine after validation.
     *
     * @param targetState The state to transition to
     * @param context     The execution context
     * @return List of domain events generated by this state change
     */
    List<DomainEvent> transitionTo(S targetState, WorkflowContext context);
}
