name: Backend CI

on:
  push:
    branches: [ "main", "develop" ]
  pull_request:
    branches: [ "main", "develop" ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Java 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: 'maven' # speeds up builds by caching dependencies
          
      - name: Ensure wrapper is executable
        run: chmod +x ./mvnw

      - name: Build, test and Quality Checks
        # This single command runs:
        # 1. Compilation
        # 2. Unit Tests (JUnit 5)
        # 3. Checkstyle (Google Java style)
        # 4. SpotBugs (static bug analysis)
        # 5. JaCoCo (test coverage check)
        env:
          JWT_SECRET: ${{ secrets.JWT_SECRET }}
        run: ./mvnw clean verify


      - name: Upload jacoco coverage report
        uses: actions/upload-artifact@v4
        if: always() #Upload even if previous step fails
        with:
          name: jacoco-report
          path: target/site/jacoco/
      